spring:
  application:
    name: cog-auth-poc
server:
  port: 8866
aws:
  cognito:
    user-pool-id: <your user pool id>
    # yaml arrays don't work use standard spring
    audiences: <coma separated list of audiences (probably your client id's in cognito), keep empty to disable validation>
    region: <your region>
